#!/usr/bin/bash
# shellcheck disable=SC2155

LIB_ROOT="$(dirname "$0")/../common"
# The common/utils.sh include needs to come first, as it includes definition
# of print_cgroup_hierarchy()
# shellcheck source=common/utils.sh
. "$LIB_ROOT/utils.sh" || exit 1
# shellcheck source=common/task-control.sh
. "$LIB_ROOT/task-control.sh" "testsuite-logs-$(print_cgroup_hierarchy)-rhel8" || exit 1

# EXIT signal handler
at_exit() {
    set +e
    exectask "journalctl-testsuite" "journalctl -b -o short-monotonic --no-hostname --no-pager"
}

set -eu
set -o pipefail

trap at_exit EXIT

### TEST PHASE ###
CGROUP_HIERARCHY="$(print_cgroup_hierarchy)"

echo "Current cgroup hierarchy: $CGROUP_HIERARCHY"
# Reflect the current cgroup hierarchy in each test VM
if [[ "$CGROUP_HIERARCHY" == unified ]]; then
    CGROUP_KERNEL_ARGS="systemd.unified_cgroup_hierarchy=1 systemd.legacy_systemd_cgroup_controller=0"
else
    CGROUP_KERNEL_ARGS="systemd.unified_cgroup_hierarchy=0 systemd.legacy_systemd_cgroup_controller=1"
fi

# To get meaningful results from coredumps collected from integration tests
# we need to store them in journal. This patchset is currently only in upcoming
# RHEL 8.3, see https://github.com/systemd-rhel/rhel-8/pull/85.
if grep -q "Storage=journal" systemd/test/test-functions; then
    COLLECT_COREDUMPS=1
else
    COLLECT_COREDUMPS=0
fi

# Enable systemd-coredump
if [[ $COLLECT_COREDUMPS -ne 0 ]]; then
    if ! coredumpctl_init; then
        echo >&2 "Failed to configure systemd-coredump/coredumpctl"
        exit 1
    fi

    # Collect any coredumps that happened during boot
    if ! exectask "coredumpctl_collect_boot" "coredumpctl_collect"; then
        echo >&2 "Detected coredump(s) during system bootup"
        exit 1
    fi
fi

set +e

### TEST PHASE ###
pushd systemd || { echo >&2 "Can't pushd to systemd"; exit 1; }

# FIXME: test-journal-flush
# A particularly ugly workaround for the flaky test-journal-flush. As the issue
# presented so far only in the QEMU TEST-24, let's skip it just there, instead
# of disabling it completely (even in the `meson test`).
#
# See: systemd/systemd#17963
# shellcheck disable=SC2016
sed -i '/TEST_LIST=/aTEST_LIST=("${TEST_LIST[@]/\\/usr\\/lib\\/systemd\\/tests\\/test-journal-flush}")' test/TEST-24-UNIT-TESTS/testsuite.sh

# FIXME: test-barrier
# This test is flaky on systems under load, which happens intermittently due
# to how meson runs the tests (in parallel).
#
# See:
#   https://github.com/systemd/systemd/commit/fd23f9c9a70e1214507641d327da40d1688b74d7
#   https://github.com/systemd/systemd/commit/a1e3f0f38b43e68ff9ea33ab1935aed4edf6ed7f
echo 'int main(void) { return 77; }' >src/test/test-barrier.c

# FIXME (not really): test-execute
# This test is not compatible with newer packages on RHEL 9 and backporting all the necessary stuff would be a
# major PITA. Since we run it in other CIs (both externally and internally), let's just not bother here.
echo 'int main(void) { return 77; }' >src/test/test-execute.c

# FIXME (also not really): test-fs-util with newer kernel
# This test fails with newer kernels, because we're missing a couple of patches in RHEL 8. Since there's no
# CentOS 8 (nor CentOS Stream 8), we run the tests on C9S and hit this issue. It's very unlikely we'll backport
# the necessary patches to RHEL 8, so drop the failing test for now.
#
# See:
#   - https://github.com/redhat-plumbers/systemd-rhel8/issues/434
sed -i '/a = strjoina(p, "\/lnk");/,/timespec_load/d' src/test/test-fs-util.c

# Run the internal unit tests (make check)
exectask "ninja-test" "meson test -C build --print-errorlogs --timeout-multiplier=3"
# Copy over meson test artifacts
[[ -d "build/meson-logs" ]] && rsync -amq --include '*.txt' --include '*/' --exclude '*' "build/meson-logs" "$LOGDIR"

# Ignore any coredumps generated by unit tests, as there's a lot of intentional crashes
coredumpctl_set_ts

## Integration test suite ##
CHECK_LIST=()
SKIP_LIST=(
    "test/TEST-16-EXTEND-TIMEOUT" # flaky test
)

if [[ "$CGROUP_HIERARCHY" == "legacy" ]]; then
    # This test explicitly requires unified cgroup hierarchy
    SKIP_LIST+=("test/TEST-19-DELEGATE")
fi

centos_ensure_qemu_symlink

## Generate a custom-tailored initrd for the integration tests
# The host initrd contains multipath modules & services which are unused
# in the integration tests and sometimes cause unexpected failures. Let's build
# a custom initrd used solely by the integration tests
#
# Set a path to the custom initrd into the INITRD variable which is read by
# the integration test suite "framework"
export INITRD="/var/tmp/ci-initramfs-$(uname -r).img"
# Copy over the original initrd, as we want to keep the custom installed
# files we installed during the bootstrap phase (i.e. we want to keep the
# command line arguments the original initrd was built with)
cp -fv "/boot/initramfs-$(uname -r).img" "$INITRD"
# Rebuild the original initrd without the multipath module
dracut -o "multipath rngd dbus-broker" -a dbus-daemon --filesystems ext4 --rebuild "$INITRD"

for t in test/TEST-??-*; do
    if [[ ${#SKIP_LIST[@]} -ne 0 ]] && in_set "$t" "${SKIP_LIST[@]}"; then
        echo -e "[SKIP] Skipping test $t\n"
        continue
    fi

    ## Configure test environment
    # Explicitly set paths to initramfs and kernel images (for QEMU tests)
    # See $INITRD above
    export KERNEL_BIN="/boot/vmlinuz-$(uname -r)"
    export KERNEL_APPEND="enforcing=0 $CGROUP_KERNEL_ARGS"
    # Set timeouts for QEMU and nspawn tests to kill them in case they get stuck
    export QEMU_TIMEOUT=1200
    export NSPAWN_TIMEOUT=600
    # Set the test dir to something predictable so we can refer to it later
    export TESTDIR="/var/tmp/systemd-test-${t##*/}"
    # Set QEMU_SMP appropriately (regarding the parallelism)
    # OPTIMAL_QEMU_SMP is part of the common/task-control.sh file
    export QEMU_SMP=$OPTIMAL_QEMU_SMP
    # Work around 'Fatal glibc error: CPU does not support x86-64-v2'
    # See:
    #   - https://bugzilla.redhat.com/show_bug.cgi?id=2060839
    #   - https://access.redhat.com/solutions/6833751
    export QEMU_OPTIONS="-cpu Nehalem"
    # Several syscalls we need are not whitelisted by default in RHEL 8's systemd, but systemd knows
    # about them, so let's tell it to whitelist all known syscalls
    export NSPAWN_ARGUMENTS="--system-call-filter=@known"

    # Suffix the $TESTDIR of each retry with an index to tell them apart
    export MANGLE_TESTDIR=1
    # FIXME: retry each task again if it fails (i.e. run each task twice at most)
    #        to work around intermittent QEMU soft lockups/ACPI timer errors
    #
    # Suffix the $TESTDIR of each retry with an index to tell them apart
    exectask_retry_p "${t##*/}" "/bin/time -v -- make -C $t setup run && touch \$TESTDIR/pass; rm -fv \$TESTDIR/*.img; test -e \$TESTDIR/pass"
    # Retried tasks are suffixed with an index, so update the $CHECK_LIST
    # array with all possible task names correctly find the respective journals
    # shellcheck disable=SC2207
    CHECK_LIST+=($(seq -f "${t}_%g" 1 "$TASK_RETRY_DEFAULT"))
done

# Wait for remaining running tasks
exectask_p_finish

# Save journals created by integration tests
for t in "${CHECK_LIST[@]}"; do
    testdir="/var/tmp/systemd-test-${t##*/}"
    if [[ -d "$testdir/journal" ]]; then
        if [[ $COLLECT_COREDUMPS -ne 0 ]]; then
            # Attempt to collect coredumps from test-specific journals as well
            exectask "${t##*/}_coredumpctl_collect" "coredumpctl_collect '$testdir/journal'"
        fi
        # Keep the journal files only if the associated test case failed
        if [[ ! -f "$testdir/pass" ]]; then
            rsync -aq "$testdir/journal" "$LOGDIR/${t##*/}"
        fi
    fi
done

## Other integration tests ##
TEST_LIST=(
    "test/test-exec-deserialization.py"
#    "test/test-network/systemd-networkd-tests.py"
)

for t in "${TEST_LIST[@]}"; do
    exectask "${t##*/}" "/bin/time -v -- ./$t"
done

if [[ $COLLECT_COREDUMPS -ne 0 ]]; then
    # Collect coredumps using the coredumpctl utility, if any
    exectask "coredumpctl_collect" "coredumpctl_collect"
fi

# Summary
show_task_summary

finish_and_exit
